[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 1303459049865613505
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Starfell is booting..."
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["starfell_logo_big"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The buttons to display on Discord 

	[[init.buttons]]
		label = "Modrinth Page"
		url = "https://modrinth.com/project/starfell"

[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is resting in"
	#The second line of text under the app name
	state = "the main menu..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["starfell_logo_big"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The buttons to display on Discord 

	[[main_menu.buttons]]
		label = "Modrinth Page"
		url = "https://modrinth.com/project/starfell"

[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a server..."
	#The second line of text under the app name
	state = "Searching for friends..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["starfell_logo_big"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The buttons to display on Discord 

	[[server_list.buttons]]
		label = "Modrinth Page"
		url = "https://modrinth.com/project/starfell"

[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a Realm..."
	#The second line of text under the app name
	state = "Browsing Realms..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["starfell_logo_big"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The buttons to display on Discord 

	[[realms_list.buttons]]
		label = "Modrinth Page"
		url = "https://modrinth.com/project/starfell"

[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is joining a game..."
	#The second line of text under the app name
	state = "Joining Game..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["starfell_logo_big"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The buttons to display on Discord 

	[[join_game.buttons]]
		label = "Modrinth Page"
		url = "https://modrinth.com/project/starfell"

[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Currently In %world%"
	#The second line of text under the app name
	state = "Playing in: %savename%"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["starfell_logo_big"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The buttons to display on Discord 

	[[single_player.buttons]]
		label = "Modrinth Page"
		url = "https://modrinth.com/project/starfell"

[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on a server"
	#The second line of text under the app name
	state = "With some friends, probably"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["starfell_logo_big"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The Asset ID/URL of the image to display as the small imageModrinth
	#The text that gets displayed when the small image is hovered
	smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The buttons to display on Discord 

	[[multi_player.buttons]]
		label = "Modrinth Page"
		url = "https://modrinth.com/project/starfell"

[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on a Realm"
	#The second line of text under the app name
	state = "With some friends, probably"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["starfell_logo_big"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Melatonin is a relaxing vanilla+ modpack developed by Ivqry in Starlight Studios. Go check it out on Modrinth!"
	#The buttons to display on Discord 

	[[realms.buttons]]
		label = "Modrinth Page"
		url = "https://modrinth.com/project/starfell"

[generic]
	#The first line of text under the app name
	description = "Exploring the world"
	#The second line of text under the app name
	state = "of Starfell"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["starfell_logo_big"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
	#The buttons to display on Discord 

	[[generic.buttons]]
		label = "Modrinth Page"
		url = "https://modrinth.com/project/starfell"

[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

[dimension_overrides]
	enabled = true

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is exploring The Overworld"
		state = "Playing in: %savename%"
		largeImageKey = ["starfell_logo_big"]
		largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
		smallImageKey = [""]
		smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"

		[[dimension_overrides.dimensions.buttons]]
			label = "Modrinth Page"
			url = "https://modrinth.com/project/starfell"


	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is exploring The Nether"
		state = "Playing in: %savename%"
		largeImageKey = ["starfell_logo_big"]
		largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
		smallImageKey = [""]
		smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"

		[[dimension_overrides.dimensions.buttons]]
			label = "Modrinth Page"
			url = "https://modrinth.com/project/starfell"


	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is exploring The End"
		state = "Playing in: %savename%"
		largeImageKey = ["starfell_logo_big"]
		largeImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"
		smallImageKey = [""]
		smallImageText = "Starfell is an Medieval RPG modpack developed by Ivqry in Starlight Studios. Check it out on Modrinth!"

		[[dimension_overrides.dimensions.buttons]]
			label = "Modrinth Page"
			url = "https://modrinth.com/project/starfell"



