StartupEvents.registry('item', event => {
	event.create('green_fabric')
	event.create('light_gray_fabric')
	event.create('gray_fabric')
	event.create('black_fabric')
	event.create('magenta_fabric')
	event.create('yellow_fabric')
	event.create('red_fabric')
	event.create('lime_fabric')
	event.create('cyan_fabric')
	event.create('light_blue_fabric')
	event.create('brown_fabric')
	event.create('purple_fabric')
	event.create('pink_fabric')
	event.create('blue_fabric')
	event.create('orange_fabric')
	event.create('white_fabric')
})