StartupEvents.registry('item', event => {
	event.create('enchanting_guide').maxStackSize(16).rarity('rare').tooltip("§7They say this tome holds the secrets\nto unlocking mythical gear...")
	event.create('mythril_core').maxStackSize(16).rarity('rare').tooltip("§7A magical core made out of mythril and diamond. They\nsay it has the ability to bend space and time...")
	event.create('waystone_key').maxStackSize(16).rarity('uncommon').tooltip("§7A mysterious key able to access the ancient waystones...")
	event.create('chain_links')
	event.create('compass_casting_mold').maxStackSize(16).rarity('common').tooltip("§7Compass Upgrade\nApplies to:\n §9Compass\n§7Ingredients:\n §9Gold, Emeralds, & Sculk")
	event.create('reinforced_iron_ingot')
	event.create('reinforced_iron_sheet')
	event.create('scrap_metal')
	event.create('reinforced_chain_links')
	event.create('reinforced_chainmail_helm', 'helmet').tier('reinforced_chainmail')
	event.create('reinforced_chainmail_shirt', 'chestplate').tier('reinforced_chainmail')
	event.create('reinforced_chainmail_leggings', 'leggings').tier('reinforced_chainmail')
	event.create('reinforced_chainmail_greaves', 'boots').tier('reinforced_chainmail')
	event.create('soul_quartz')
})

//event.create('qliphoth_cane', 'sword').maxStackSize(1).rarity('common').tier('silver').attackDamageBaseline(4.0).speedBaseline(-2.4).tooltip("§7'While thy branches mix with mine;\nand our roots together join!'")
//event.create('soul_scythe', 'sword').maxStackSize(1).fireResistant(true).maxDamage(0.0).attackDamageBaseline(10.0).speedBaseline(-3.0)