ItemEvents.modification(event => {
	function stackTo64(x) {
		event.modify(x, item => {item.maxStackSize = 64})
	}
	function stackTo48(x) {
		event.modify(x, item => {item.maxStackSize = 48})
	}
	function stackTo32(x) {
		event.modify(x, item => {item.maxStackSize = 32})
	}
	function stackTo24(x) {
		event.modify(x, item => {item.maxStackSize = 24})
	}
	function stackTo16(x) {
		event.modify(x, item => {item.maxStackSize = 16})
	}
	function stackTo12(x) {
		event.modify(x, item => {item.maxStackSize = 12})
	}
	function stackTo8(x) {
		event.modify(x, item => {item.maxStackSize = 8})
	}
	function stackTo4(x) {
		event.modify(x, item => {item.maxStackSize = 4})
	}
	function stackTo2(x) {
		event.modify(x, item => {item.maxStackSize = 2})
	}
	
	//Combat Edibles
	stackTo2('minecraft:enchanted_golden_apple')
	stackTo8('minecraft:golden_apple')
	
	//Potions
	stackTo16('minecraft:potion')
	stackTo16('minecraft:splash_potion')
	stackTo16('minecraft:lingering_potion')
	
	//Placeable Foods
	stackTo16('minecraft:cake')
	stackTo16('bountifulfares:cocoa_cake')
	stackTo16('minecraft:pumpkin_pie')
	stackTo16('farmersdelight:apple_pie')
	stackTo16('farmersdelight:sweet_berry_cheesecake')
	stackTo16('farmersdelight:chocolate_pie')
	stackTo16('brewinandchewin:quiche')
	stackTo16('brewinandchewin:pizza')
	stackTo16('farmersdelight:stuffed_pumpkin_block')
	stackTo16('farmersdelight:roast_chicken_block')
	stackTo16('farmersdelight:honey_glazed_ham_block')
	stackTo16('farmersdelight:shepherds_pie_block')
	stackTo16('farmersdelight:rice_roll_medley_block')
	stackTo16('mynethersdelight:striderloaf')
	stackTo16('mynethersdelight:ghasta_with_cream')
	stackTo16('mynethersdelight:magma_cake')
	stackTo16('supplementaries:pancake')
	stackTo16('bountifulfares:artisan_cookie')
	
	//Items
	stackTo16('create:blaze_cake')
	stackTo16('minecraft:dragon_breath')
	stackTo16('minecraft:oak_boat')
	stackTo16('minecraft:oak_chest_boat')
	stackTo16('minecraft:spruce_boat')
	stackTo16('minecraft:spruce_chest_boat')
	stackTo16('minecraft:birch_boat')
	stackTo16('minecraft:birch_chest_boat')
	stackTo16('minecraft:jungle_boat')
	stackTo16('minecraft:jungle_chest_boat')
	stackTo16('minecraft:acacia_boat')
	stackTo16('minecraft:acacia_chest_boat')
	stackTo16('minecraft:dark_oak_boat')
	stackTo16('minecraft:dark_oak_chest_boat')
	stackTo16('minecraft:mangrove_boat')
	stackTo16('minecraft:mangrove_chest_boat')
	stackTo16('minecraft:minecart')
	stackTo16('minecraft:chest_minecart')
	stackTo16('minecraft:furnace_minecart')
	stackTo16('minecraft:tnt_minecart')
	stackTo16('minecraft:hopper_minecart')
	stackTo16('minecraft:command_block_minecart')
	stackTo16('supplementaries:dispenser_minecart')
	stackTo16('minecraft:spyglass')
	stackTo16('minecraft:compass')
	stackTo16('minecraft:recovery_compass')
	stackTo16('minecraft:clock')
	stackTo16('supplementaries:altimeter')
	stackTo16('minecraft:white_bed')
	stackTo16('minecraft:orange_bed')
	stackTo16('minecraft:magenta_bed')
	stackTo16('minecraft:light_blue_bed')
	stackTo16('minecraft:yellow_bed')
	stackTo16('minecraft:lime_bed')
	stackTo16('minecraft:pink_bed')
	stackTo16('minecraft:gray_bed')
	stackTo16('minecraft:light_gray_bed')
	stackTo16('minecraft:cyan_bed')
	stackTo16('minecraft:purple_bed')
	stackTo16('minecraft:blue_bed')
	stackTo16('minecraft:brown_bed')
	stackTo16('minecraft:green_bed')
	stackTo16('minecraft:red_bed')
	stackTo16('minecraft:black_bed')
	stackTo16('minecraft:saddle')
	stackTo16('minecraft:iron_horse_armor')
	stackTo16('minecraft:golden_horse_armor')
	stackTo16('minecraft:diamond_horse_armor')
	stackTo16('minecraft:leather_horse_armor')
	stackTo16('minecraft:bucket')
	stackTo16('minecraft:music_disc_13')
	stackTo16('minecraft:music_disc_cat')
	stackTo16('minecraft:music_disc_blocks')
	stackTo16('minecraft:music_disc_chirp')
	stackTo16('minecraft:music_disc_far')
	stackTo16('minecraft:music_disc_mall')
	stackTo16('minecraft:music_disc_mellohi')
	stackTo16('minecraft:music_disc_stal')
	stackTo16('minecraft:music_disc_strad')
	stackTo16('minecraft:music_disc_ward')
	stackTo16('minecraft:music_disc_11')
	stackTo16('minecraft:music_disc_wait')
	stackTo16('minecraft:music_disc_otherside')
	stackTo16('minecraft:music_disc_5')
	stackTo16('minecraft:music_disc_pigstep')
	stackTo64('minecraft:snowball')
	stackTo64('minecraft:ender_pearl')
	stackTo64('minecraft:egg')
	stackTo64('farmersdelight:rotten_tomato')
	stackTo64('minecraft:oak_sign')
	stackTo64('minecraft:spruce_sign')
	stackTo64('minecraft:birch_sign')
	stackTo64('minecraft:jungle_sign')
	stackTo64('minecraft:acacia_sign')
	stackTo64('minecraft:dark_oak_sign')
	stackTo64('minecraft:mangrove_sign')
	stackTo64('minecraft:crimson_sign')
	stackTo64('minecraft:warped_sign')
	stackTo64('supplementaries:hanging_sign_oak')
	stackTo64('supplementaries:hanging_sign_spruce')
	stackTo64('supplementaries:hanging_sign_birch')
	stackTo64('supplementaries:hanging_sign_jungle')
	stackTo64('supplementaries:hanging_sign_acacia')
	stackTo64('supplementaries:hanging_sign_dark_oak')
	stackTo64('supplementaries:hanging_sign_mangrove')
	stackTo64('supplementaries:hanging_sign_crimson')
	stackTo64('supplementaries:hanging_sign_warped')
	stackTo64('supplementaries:sign_post_oak')
	stackTo64('supplementaries:sign_post_spruce')
	stackTo64('supplementaries:sign_post_birch')
	stackTo64('supplementaries:sign_post_jungle')
	stackTo64('supplementaries:sign_post_acacia')
	stackTo64('supplementaries:sign_post_dark_oak')
	stackTo64('supplementaries:sign_post_mangrove')
	stackTo64('supplementaries:sign_post_crimson')
	stackTo64('supplementaries:sign_post_warped')
	stackTo64('minecraft:armor_stand')
	stackTo64('minecraft:white_banner')
	stackTo64('minecraft:orange_banner')
	stackTo64('minecraft:magenta_banner')
	stackTo64('minecraft:light_blue_banner')
	stackTo64('minecraft:yellow_banner')
	stackTo64('minecraft:lime_banner')
	stackTo64('minecraft:pink_banner')
	stackTo64('minecraft:gray_banner')
	stackTo64('minecraft:light_gray_banner')
	stackTo64('minecraft:cyan_banner')
	stackTo64('minecraft:purple_banner')
	stackTo64('minecraft:blue_banner')
	stackTo64('minecraft:brown_banner')
	stackTo64('minecraft:green_banner')
	stackTo64('minecraft:red_banner')
	stackTo64('minecraft:black_banner')
	stackTo64('supplementaries:flag_white')
	stackTo64('supplementaries:flag_orange')
	stackTo64('supplementaries:flag_magenta')
	stackTo64('supplementaries:flag_light_blue')
	stackTo64('supplementaries:flag_yellow')
	stackTo64('supplementaries:flag_lime')
	stackTo64('supplementaries:flag_pink')
	stackTo64('supplementaries:flag_gray')
	stackTo64('supplementaries:flag_light_gray')
	stackTo64('supplementaries:flag_cyan')
	stackTo64('supplementaries:flag_purple')
	stackTo64('supplementaries:flag_blue')
	stackTo64('supplementaries:flag_brown')
	stackTo64('supplementaries:flag_green')
	stackTo64('supplementaries:flag_red')
	stackTo64('supplementaries:flag_black')
})