# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				villager = true
				sheep = true
				pig = true
				chicken = true
				iron_golem = true
				item = true
				chest_minecart = true
				cow = true
				rabbit = true
				bat = true
				squid = true
				skeleton = true
				spider = true
				zombie = true
				creeper = true
				drowned = true
				enderman = true
				axolotl = true
				glow_squid = true
				bee = true
				witch = true
				experience_orb = true
				zombie_villager = true
				parrot = true
				arrow = true
				salmon = true
				lightning_bolt = true
				fox = true
				slime = true
				wolf = true
				horse = true
				item_frame = true
				piglin = true
				hoglin = true
				zombified_piglin = true
				strider = true
				ghast = true
				fireball = true
				piglin_brute = true
				magma_cube = true
				wither_skeleton = true
				blaze = true
				small_fireball = true
				painting = true
				cat = true
				leash_knot = true
				eye_of_ender = true
				wandering_trader = true
				trader_llama = true
				cod = true
				armor_stand = true
				goat = true
				silverfish = true
				ender_dragon = true
				dragon_fireball = true
				area_effect_cloud = true
				ender_pearl = true
				endermite = true
				polar_bear = true
				turtle = true
				donkey = true
				dolphin = true
				tropical_fish = true
				pillager = true
				illusioner = true
				pufferfish = true
				cave_spider = true
				phantom = true
				frog = true
				boat = true
				panda = true
				llama = true
				husk = true
				egg = true
				trident = true
				allay = true
				vindicator = true
				ravager = true
				potion = true
				evoker = true
				vex = true
				evoker_fangs = true
				firework_rocket = true
				chest_boat = true
				elder_guardian = true
				guardian = true
				camel = true
				experience_bottle = true
				ocelot = true
				llama_spit = true
				shulker = true
				stray = true
				tnt_minecart = true
				minecart = true
				spectral_arrow = true
				fishing_bobber = true
				zombie_horse = true
				furnace_minecart = true
				skeleton_horse = true
				zoglin = true
				wither = true
				wither_skull = true
				warden = true
				mooshroom = true
				snow_golem = true

			[light_sources.settings.entities.naturalist]
				butterfly = true
				firefly = true
				lizard = true
				deer = true
				duck = true
				snail = true
				tortoise = true
				boar = true
				zebra = true
				bass = true
				rattlesnake = true
				rhino = true
				finch = true
				robin = true
				coral_snake = true
				cardinal = true
				snake = true
				giraffe = true
				vulture = true
				bear = true
				canary = true
				sparrow = true
				bluejay = true
				lion = true
				elephant = true
				alligator = true
				dragonfly = true
				catfish = true
				hippo = true
				caterpillar = true
				lizard_tail = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.friendsandfoes]
				rascal = true
				mauler = true
				copper_golem = true
				glare = true
				moobloom = true
				iceologer = true
				player_illusion = true
				wildfire = true
				tuff_golem = true
				crab = true
				ice_chunk = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true
				bamboo_creeper = true
				savannah_creeper = true
				jungle_creeper = true
				dripstone_creeper = true
				hills_creeper = true
				dark_oak_creeper = true
				spruce_creeper = true
				snowy_creeper = true
				ocean_creeper = true
				beach_creeper = true
				desert_creeper = true
				badlands_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = true
				cave_enderman = true
				crimson_forest_enderman = true
				warped_forest_enderman = true
				soulsand_valley_enderman = true
				nether_wastes_enderman = true
				dark_oak_enderman = true
				end_enderman = true
				flower_fields_enderman = true
				snowy_enderman = true
				swamp_enderman = true
				desert_enderman = true
				coral_enderman = true
				badlands_enderman = true
				ancient_pearl = true
				axolotl_pet_enderman = true
				pet_enderman = true
				hammerhead_pet_enderman = true
				corrupted_pearl = true
				ice_spikes_enderman = true
				end_islands_enderman = true
				spirit = true
				bubble_pearl = true
				windswept_hills_enderman = true

			[light_sources.settings.entities.create]
				super_glue = true
				stationary_contraption = true
				crafting_blueprint = true
				contraption = true

			[light_sources.settings.entities.sleep_tight]
				bed_entity = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				penguin = true
				coconut_crab = true

			[light_sources.settings.entities.supplementaries]
				hat_stand = true
				red_merchant = true
				rope_arrow = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.enchancement]
				ice_shard = true
				amethyst_shard = true
				brimstone = true
				grapple_fishing_bobber = true

			[light_sources.settings.entities.spelunkery]
				dust_bunny = true

			[light_sources.settings.entities.amarite]
				amarite_disc = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.spell_engine]
				spell_projectile = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.mcdar]
				golem_kit_golem = true
				tasty_bone_wolf = true
				wonderful_wheat_llama = true
				enchanted_blue_sheep = true

			[light_sources.settings.entities.medievalorigins]
				summon_skeleton = true

			[light_sources.settings.entities.digs_dnd_origins]
				toy_frog = true

			[light_sources.settings.entities.bountifulfares]
				flour = true

			[light_sources.settings.entities.mynethersdelight]
				strider_rock = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

